# Generated by Django 4.2.28 on 2026-02-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_update_verbose_names_add_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
    ]
